/**
 * Shell completion.
 *
 * The command tree is fully static (every endpoint is a GET, nothing is
 * discovered at runtime), so the scripts are generated by walking the citty
 * definitions once and baking the result in. The only dynamic part is the profile
 * list, which the scripts read from `ris __profiles`.
 */
import type { ArgsDef, CommandDef } from "citty";

export const SHELLS = ["bash", "zsh", "fish"] as const;
export type Shell = (typeof SHELLS)[number];

export interface FlagSpec {
  /** Long form without dashes, e.g. `api-url`. */
  name: string;
  shortAliases: string[];
  description: string;
  takesValue: boolean;
  options?: string[];
}

export interface CommandNode {
  name: string;
  aliases: string[];
  description: string;
  subCommands: CommandNode[];
  flags: FlagSpec[];
}

async function resolve<T>(value: T | (() => T | Promise<T>) | undefined): Promise<T | undefined> {
  return typeof value === "function" ? (value as () => Promise<T>)() : value;
}

function toArray(value: string | string[] | undefined): string[] {
  if (value === undefined) return [];
  return Array.isArray(value) ? value : [value];
}

/** Walks a citty command definition into a shell-agnostic description. */
export async function describeCommand(
  command: CommandDef,
  fallbackName = "",
): Promise<CommandNode> {
  const meta = await resolve(command.meta);
  const args = ((await resolve(command.args)) ?? {}) as ArgsDef;

  const flags: FlagSpec[] = [];
  for (const [name, definition] of Object.entries(args)) {
    if (definition.type === "positional") continue;
    flags.push({
      name,
      shortAliases: toArray((definition as { alias?: string | string[] }).alias),
      description: definition.description ?? "",
      takesValue: definition.type !== "boolean",
      options: (definition as { options?: string[] }).options,
    });
  }

  const subCommands: CommandNode[] = [];
  const subDefs = ((await resolve(command.subCommands)) ?? {}) as Record<string, CommandDef>;
  for (const [name, subDef] of Object.entries(subDefs)) {
    const resolved = await resolve<CommandDef>(subDef as CommandDef);
    if (!resolved) continue;
    const child = await describeCommand(resolved, name);
    // Hidden commands (e.g. __profiles) stay out of completion.
    if (child.name.startsWith("__")) continue;
    subCommands.push({ ...child, name });
  }

  return {
    name: meta?.name ?? fallbackName,
    aliases: toArray(meta?.alias),
    description: meta?.description ?? "",
    subCommands,
    flags: flags.sort((a, b) => a.name.localeCompare(b.name)),
  };
}

/** Every command path in the tree, as space-joined canonical names. */
function walk(node: CommandNode, prefix: string[] = []): { path: string[]; node: CommandNode }[] {
  const here = { path: prefix, node };
  return [here, ...node.subCommands.flatMap((child) => walk(child, [...prefix, child.name]))];
}

function flagTokens(node: CommandNode): string[] {
  return node.flags.flatMap((flag) => [
    `--${flag.name}`,
    ...flag.shortAliases.map((alias) => `-${alias}`),
  ]);
}

/** Flags whose values complete from a live command rather than a static list. */
const DYNAMIC_FLAGS: Record<string, string> = { profile: "__profiles" };

/**
 * Known values for flags that are declared as plain strings because they accept
 * repeated or comma-separated values, so citty carries no `options` for them.
 */
const EXTRA_FLAG_VALUES: Record<string, string[]> = {
  "type-group": ["Urteil", "Beschluss", "other"],
};

/** Enumerable positional values, keyed by canonical command path. */
const POSITIONAL_VALUES: Record<string, string[]> = {
  completion: [...SHELLS],
};

/** Flags whose argument is a path, where filename completion is the right answer. */
const FILE_FLAGS = ["output-file"];

function valuesForFlag(flag: FlagSpec): string[] | undefined {
  if (flag.options && flag.options.length > 0) return flag.options;
  return EXTRA_FLAG_VALUES[flag.name];
}

/**
 * A shell case pattern matching every spelling of a flag, so that `-p` completes
 * its values just as `--profile` does.
 */
function flagPattern(name: string, aliases: string[]): string {
  return [`--${name}`, ...aliases.map((alias) => `-${alias}`)].join("|");
}

/** Short aliases per flag name, collected across the whole tree. */
function aliasIndex(nodes: { node: CommandNode }[]): Map<string, string[]> {
  const index = new Map<string, string[]>();
  for (const { node } of nodes) {
    for (const flag of node.flags) {
      const existing = index.get(flag.name) ?? [];
      index.set(flag.name, [...new Set([...existing, ...flag.shortAliases])]);
    }
  }
  return index;
}

function shellSingleQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

/** Descriptions go into completion menus, so keep them to one clean line. */
function oneLine(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

export function generateBash(root: CommandNode): string {
  const nodes = walk(root);
  const aliases = aliasIndex(nodes);

  const subCommandCases = nodes
    .filter(({ node }) => node.subCommands.length > 0)
    .map(({ path, node }) => {
      const names = node.subCommands.flatMap((child) => [child.name, ...child.aliases]);
      return `    ${shellSingleQuote(path.join(" "))}) echo ${shellSingleQuote(names.join(" "))} ;;`;
    })
    .join("\n");

  const flagCases = nodes
    .map(({ path, node }) => {
      const tokens = flagTokens(node);
      if (tokens.length === 0) return undefined;
      return `    ${shellSingleQuote(path.join(" "))}) echo ${shellSingleQuote(tokens.join(" "))} ;;`;
    })
    .filter(Boolean)
    .join("\n");

  // Alias → canonical name, so lookups only ever use canonical paths.
  const aliasCases = nodes
    .flatMap(({ node }) => node.subCommands)
    .flatMap((child) => child.aliases.map((alias) => ({ alias, name: child.name })))
    .map(({ alias, name }) => `    ${shellSingleQuote(alias)}) echo ${shellSingleQuote(name)} ;;`)
    .join("\n");

  const optionCases = [
    ...new Map(
      nodes
        .flatMap(({ node }) => node.flags)
        .map((flag) => [flag.name, valuesForFlag(flag)] as const)
        .filter((entry): entry is readonly [string, string[]] => entry[1] !== undefined),
    ),
  ]
    .map(
      ([name, options]) =>
        `    ${flagPattern(name, aliases.get(name) ?? [])}) echo ${shellSingleQuote(options.join(" "))} ;;`,
    )
    .join("\n");

  const dynamicCases = Object.entries(DYNAMIC_FLAGS)
    .map(
      ([flag, command]) =>
        `    ${flagPattern(flag, aliases.get(flag) ?? [])}) "\${ris_bin}" ${command} 2>/dev/null ;;`,
    )
    .join("\n");

  const positionalCases = Object.entries(POSITIONAL_VALUES)
    .map(
      ([path, values]) =>
        `    ${shellSingleQuote(path)}) echo ${shellSingleQuote(values.join(" "))} ;;`,
    )
    .join("\n");

  const fileFlagPattern = FILE_FLAGS.flatMap((name) => [`--${name}`, "-O"]).join("|");

  return `# bash completion for ris. Install with:
#   ris completion bash > /usr/local/etc/bash_completion.d/ris
# or source it directly from ~/.bashrc:
#   eval "$(ris completion bash)"

_ris_canonical() {
  case "$1" in
${aliasCases}
    *) echo "$1" ;;
  esac
}

_ris_subcommands() {
  case "$1" in
${subCommandCases}
    *) echo "" ;;
  esac
}

_ris_flags() {
  case "$1" in
${flagCases}
    *) echo "" ;;
  esac
}

_ris_flag_values() {
  local ris_bin="$2"
  case "$1" in
${optionCases}
${dynamicCases}
    *) echo "" ;;
  esac
}

_ris_positional_values() {
  case "$1" in
${positionalCases}
    *) echo "" ;;
  esac
}

_ris() {
  local cur prev path word canonical candidates i
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  COMPREPLY=()

  # A path-valued flag: hand over to filename completion.
  case "\${prev}" in
    ${fileFlagPattern})
      COMPREPLY=( $(compgen -f -- "\${cur}") )
      return 0
      ;;
  esac

  # Values for the flag immediately before the cursor.
  candidates="$(_ris_flag_values "\${prev}" "\${COMP_WORDS[0]}")"
  if [ -n "\${candidates}" ]; then
    COMPREPLY=( $(compgen -W "\${candidates}" -- "\${cur}") )
    return 0
  fi

  # Descend the command tree, stopping at the first word that is not a subcommand.
  path=""
  i=1
  while [ "\${i}" -lt "\${COMP_CWORD}" ]; do
    word="\${COMP_WORDS[i]}"
    case "\${word}" in
      -*) ;;
      *)
        canonical="$(_ris_canonical "\${word}")"
        case " $(_ris_subcommands "\${path}") " in
          *" \${word} "*)
            if [ -z "\${path}" ]; then path="\${canonical}"; else path="\${path} \${canonical}"; fi
            ;;
        esac
        ;;
    esac
    i=$((i + 1))
  done

  case "\${cur}" in
    -*) candidates="$(_ris_flags "\${path}")" ;;
    *)
      candidates="$(_ris_subcommands "\${path}")"
      # A leaf command's positional is usually free text (search terms, a document
      # number, an ELI), which cannot be completed — offer nothing rather than a
      # misleading directory listing.
      if [ -z "\${candidates}" ]; then
        candidates="$(_ris_positional_values "\${path}")"
      fi
      ;;
  esac

  COMPREPLY=( $(compgen -W "\${candidates}" -- "\${cur}") )
  return 0
}

complete -F _ris ris
`;
}

export function generateZsh(root: CommandNode): string {
  const nodes = walk(root);
  const aliases = aliasIndex(nodes);

  // name:description pairs, which _describe renders in the completion menu.
  const subCommandCases = nodes
    .filter(({ node }) => node.subCommands.length > 0)
    .map(({ path, node }) => {
      const entries = node.subCommands.map((child) => {
        const label = [child.name, ...child.aliases].join(",");
        return shellSingleQuote(`${label}:${oneLine(child.description)}`);
      });
      return `    ${shellSingleQuote(path.join(" "))}) _ris_reply=(${entries.join(" ")}) ;;`;
    })
    .join("\n");

  const flagCases = nodes
    .map(({ path, node }) => {
      if (node.flags.length === 0) return undefined;
      const entries = node.flags.flatMap((flag) => [
        shellSingleQuote(`--${flag.name}:${oneLine(flag.description)}`),
        ...flag.shortAliases.map((alias) =>
          shellSingleQuote(`-${alias}:${oneLine(flag.description)}`),
        ),
      ]);
      return `    ${shellSingleQuote(path.join(" "))}) _ris_reply=(${entries.join(" ")}) ;;`;
    })
    .filter(Boolean)
    .join("\n");

  const aliasCases = nodes
    .flatMap(({ node }) => node.subCommands)
    .flatMap((child) => child.aliases.map((alias) => ({ alias, name: child.name })))
    .map(({ alias, name }) => `    ${shellSingleQuote(alias)}) echo ${shellSingleQuote(name)} ;;`)
    .join("\n");

  const optionCases = [
    ...new Map(
      nodes
        .flatMap(({ node }) => node.flags)
        .map((flag) => [flag.name, valuesForFlag(flag)] as const)
        .filter((entry): entry is readonly [string, string[]] => entry[1] !== undefined),
    ),
  ]
    .map(
      ([name, options]) =>
        `    ${flagPattern(name, aliases.get(name) ?? [])}) _ris_values=(${options.join(" ")}) ;;`,
    )
    .join("\n");

  const dynamicCases = Object.entries(DYNAMIC_FLAGS)
    .map(
      ([flag, command]) =>
        `    ${flagPattern(flag, aliases.get(flag) ?? [])}) _ris_values=(\${(f)"$(ris ${command} 2>/dev/null)"}) ;;`,
    )
    .join("\n");

  const fileFlagCases = FILE_FLAGS.flatMap((name) => [`--${name}`, "-O"]).join("|");

  const positionalCases = Object.entries(POSITIONAL_VALUES)
    .map(([path, values]) => `      ${shellSingleQuote(path)}) _ris_reply=(${values.join(" ")}) ;;`)
    .join("\n");

  return `#compdef ris
# zsh completion for ris. Install with:
#   ris completion zsh > "\${fpath[1]}/_ris"
# then restart your shell.

_ris_canonical() {
  case "$1" in
${aliasCases}
    *) echo "$1" ;;
  esac
}

_ris() {
  local -a _ris_reply _ris_values
  local cur prev path word canonical subs

  cur="\${words[CURRENT]}"
  prev="\${words[CURRENT-1]}"

  # A path-valued flag: hand over to zsh's file completion.
  case "\${prev}" in
    ${fileFlagCases}) _files; return ;;
  esac

  case "\${prev}" in
${optionCases}
${dynamicCases}
  esac
  if (( \${#_ris_values} )); then
    compadd -- \${_ris_values}
    return
  fi

  path=""
  local i=2
  while (( i < CURRENT )); do
    word="\${words[i]}"
    if [[ "\${word}" != -* ]]; then
      canonical="$(_ris_canonical "\${word}")"
      _ris_reply=()
      case "\${path}" in
${subCommandCases}
      esac
      # Only descend when the word really is a subcommand at this level.
      subs="\${_ris_reply[*]}"
      if [[ " \${subs} " == *"\${word}"* ]]; then
        if [[ -z "\${path}" ]]; then path="\${canonical}"; else path="\${path} \${canonical}"; fi
      fi
    fi
    (( i++ ))
  done

  _ris_reply=()
  if [[ "\${cur}" == -* ]]; then
    case "\${path}" in
${flagCases}
    esac
    (( \${#_ris_reply} )) && _describe -t flags 'flag' _ris_reply
  else
    case "\${path}" in
${subCommandCases}
    esac
    if (( \${#_ris_reply} )); then
      _describe -t commands 'command' _ris_reply
      return
    fi
    # A leaf command's positional is usually free text (search terms, a document
    # number, an ELI), which cannot be completed — offer nothing rather than a
    # misleading file listing.
    case "\${path}" in
${positionalCases}
    esac
    (( \${#_ris_reply} )) && compadd -- \${_ris_reply}
  fi
}

_ris "$@"
`;
}

export function generateFish(root: CommandNode): string {
  const lines = [
    "# fish completion for ris. Install with:",
    "#   ris completion fish > ~/.config/fish/completions/ris.fish",
    "",
    "# Commands are only offered where no command has been chosen yet, so the",
    "# condition lists every command name and alias as a seen-command guard.",
    "",
  ];

  const topNames = root.subCommands.flatMap((child) => [child.name, ...child.aliases]);

  for (const child of root.subCommands) {
    const description = shellSingleQuote(oneLine(child.description));
    for (const name of [child.name, ...child.aliases]) {
      lines.push(`complete -c ris -n '__fish_use_subcommand' -a ${name} -d ${description}`);
    }
  }

  lines.push("");
  for (const child of root.subCommands) {
    if (child.subCommands.length === 0) continue;
    const seen = [child.name, ...child.aliases].join(" ");
    const subNames = child.subCommands.flatMap((sub) => [sub.name, ...sub.aliases]);
    for (const sub of child.subCommands) {
      const description = shellSingleQuote(oneLine(sub.description));
      for (const name of [sub.name, ...sub.aliases]) {
        lines.push(
          `complete -c ris -n '__fish_seen_subcommand_from ${seen}; and not __fish_seen_subcommand_from ${subNames.join(" ")}' -a ${name} -d ${description}`,
        );
      }
    }
  }

  lines.push("");
  for (const [path, values] of Object.entries(POSITIONAL_VALUES)) {
    const segments = path.split(" ");
    const condition = segments
      .map((segment) => `__fish_seen_subcommand_from ${segment}`)
      .join("; and ");
    lines.push(`complete -c ris -n '${condition}' -f -a ${shellSingleQuote(values.join(" "))}`);
  }

  lines.push("");
  for (const { path, node } of walk(root)) {
    if (node.flags.length === 0) continue;

    // Root-level flags apply when no command has been chosen; nested flags when
    // the enclosing command names have been seen.
    const condition =
      path.length === 0
        ? `-n 'not __fish_seen_subcommand_from ${topNames.join(" ")}'`
        : `-n '${path.map((segment) => `__fish_seen_subcommand_from ${segment}`).join("; and ")}'`;

    for (const flag of node.flags) {
      const parts = ["complete -c ris", condition, `-l ${flag.name}`];
      for (const alias of flag.shortAliases) parts.push(`-s ${alias}`);
      if (!flag.takesValue) parts.push("-f");
      const values = valuesForFlag(flag);
      if (values) {
        parts.push(`-x -a ${shellSingleQuote(values.join(" "))}`);
      } else if (DYNAMIC_FLAGS[flag.name]) {
        parts.push(`-x -a '(ris ${DYNAMIC_FLAGS[flag.name]} 2>/dev/null)'`);
      } else if (FILE_FLAGS.includes(flag.name)) {
        // -r without -x lets fish fall back to filename completion.
        parts.push("-r -F");
      } else if (flag.takesValue) {
        parts.push("-x");
      }
      parts.push(`-d ${shellSingleQuote(oneLine(flag.description))}`);
      lines.push(parts.join(" "));
    }
  }

  return `${lines.join("\n")}\n`;
}

export function generate(shell: Shell, root: CommandNode): string {
  switch (shell) {
    case "bash":
      return generateBash(root);
    case "zsh":
      return generateZsh(root);
    case "fish":
      return generateFish(root);
  }
}
